# image: "rust:latest"

stages:
  - spell-check
  - coverage-check
  # - deploy

test:spell:
  stage: cpell-check
  image: node:latest

  before_script:
    - npm install -g cspell

  script:
    - cspell '**/*'
  allow_failure: false 

test:coverage:
  stage: coverage-check
  image: rust:latest

  before_script:
    - rustc --version && cargo --version
    - rustup override set nightly-2025-08-06
    - rustup component add llvm-tools-preview
    - which cargo-llvm-cov || cargo install cargo-llvm-cov

  script:
    - cargo llvm-cov --branch --lcov --output-path coverage.lcov
    - cargo llvm-cov report --branch --cobertura --output-path coverage.xml
    - cargo llvm-cov report --branch --html
    - apt-get update && apt-get install -y lcov
    - lcov --summary coverage.lcov --ignore-errors inconsistent
  
  coverage: '/lines\.+: (\d+.\d+)%/'

  artifacts:
    when: always
    paths:
      - coverage.xml
      - coverage.lcov
      - target/llvm-cov/html/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  script: echo "Not defined yet"
  environment: production
